;2)1)A:

    ;  DATA:ENTRADA
    ;  STROBE:ENTRADA
    ;  BUSY:SALIDA

;2)1)B:

    ;  IMPRIME:  O  A  A

;2)1)C:

    ;SI NO EXISTIERA LA SEÑAL
    ;DE STROBE, AL IMPRIMIR "AA"
    ;SE IMPRIMIRIAN MUCHAS A

    ;EJEMPLO:AAAAAAAAAAAAAAAA

ORG 2000H  ;ESTO ES PARA GUARDARLO XD NO TENER EN CUENTA
MOV AL,1
END