HAND_DATO EQU 40H
HAND_ESTA EQU 41H

     ORG 1000H
MSJ  DB "INGENIERIA E INFORMATICA"
FIN  DB ?
  
     ORG 2000H
     IN AL, HAND_ESTA
     AND AL, 07FH
     OUT HAND_ESTA, AL
     MOV BX, OFFSET MSJ
POLL:IN AL, HAND_ESTA
     AND AL, 1
     JNZ POLL
     MOV AL, [BX]
     OUT HAND_DATO, AL
     INC BX
     CMP BX, OFFSET FIN
     JNZ POLL
     INT 0
END