      ORG 1000H			;FALTA TERMINAR (DEBO AGREGAR EL FOR PARA LOS 5 INTENTOS)
CARP1 DB 031H    ;CARP1 = CARACTER PREDEFINIDO
CARP2 DB 032H
CARP3 DB 033H
CARP4 DB 034H
CARI1 DB ?    ;CARI1 = CARACTER INGRESADO
CARI2 DB ?
CARI3 DB ?
CARI4 DB ?
MENEN DB "INGRESE LOS 4 DIGITOS DE LA CONTRASEÑA:"    ;MENSAJE ENTRADA
MENSI DB "ACCESO PERMITIDO :)"    ;MENSAJE "SI"
MENNO DB "ACCESO DENEGADO >:v"    ;MENSAJE "NO"
SALTO DB 0AH
MINTE DB "CONTRASEÑA INVALIDA, INTENTE NUEVAMENTE:"
MEFIN DB ?
      ORG 2000H
      MOV BX, OFFSET MENEN
      MOV AL, OFFSET MENSI - OFFSET MENEN
      INT 7

      MOV DL, 0
      MOV DH, 6    ;5 INTENTOS PERMITIDOS

FOR:  INC DL
      CMP DL, DH
      JZ DEN
      
      MOV BX, OFFSET CARI1    
      INT 6                  ;INGRESAMOS EL PRIMER DIGITO 
      MOV BX, OFFSET CARI2
      INT 6                  ;INGRESAMOS EL SEGUNDO DIGITO 
      MOV BX, OFFSET CARI3
      INT 6                  ;INGRESAMOS EL TERCER DIGITO 
      MOV BX, OFFSET CARI4
      INT 6                  ;INGRESAMOS EL CUARTO DIGITO

      MOV BH, CARP1
      MOV BL, CARI1
      CMP BH, BL
      JZ  DIG2
      JMP MDEN

DIG2: MOV BH, CARP2
      MOV BL, CARI2
      CMP BH, BL
      JZ DIG3
      JMP MDEN

DIG3: MOV BH, CARP3
      MOV BL, CARI3
      CMP BH, BL
      JZ DIG4
      JMP MDEN

DIG4: MOV BH, CARP4
      MOV BL, CARI4
      CMP BH, BL
      JZ PER
      JMP MDEN

DEN:  MOV AL, 1
      MOV BX, OFFSET SALTO
      INT 7
      MOV AL, OFFSET SALTO - OFFSET MENNO
      MOV BX, OFFSET MENNO
      INT 7
      JMP FIN

MDEN: MOV AL, 1
      MOV BX, OFFSET SALTO
      INT 7
      MOV AL, OFFSET MEFIN - OFFSET MINTE
      MOV BX, OFFSET MINTE
      INT 7
      JMP FOR

PER:  MOV AL, 1
      MOV BX, OFFSET SALTO
      INT 7
      MOV AL, OFFSET MENNO - OFFSET MENSI
      MOV BX, OFFSET MENSI
      INT 7
      JMP FIN
FIN:  HLT

END